/* tslint:disable */
/* eslint-disable */
/**
 * Solar Monitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Alert
 */
export interface Alert {
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    plantId?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the Alert interface.
 */
export function instanceOfAlert(value: object): value is Alert {
    return true;
}

export function AlertFromJSON(json: any): Alert {
    return AlertFromJSONTyped(json, false);
}

export function AlertFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alert {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'plantId': json['plantId'] == null ? undefined : json['plantId'],
        'type': json['type'] == null ? undefined : json['type'],
        'message': json['message'] == null ? undefined : json['message'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function AlertToJSON(json: any): Alert {
    return AlertToJSONTyped(json, false);
}

export function AlertToJSONTyped(value?: Alert | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'plantId': value['plantId'],
        'type': value['type'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

