/* tslint:disable */
/* eslint-disable */
/**
 * Solar Monitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Plant
 */
export interface Plant {
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof Plant
     */
    capacityKw?: number;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    status?: string;
}

/**
 * Check if a given object implements the Plant interface.
 */
export function instanceOfPlant(value: object): value is Plant {
    return true;
}

export function PlantFromJSON(json: any): Plant {
    return PlantFromJSONTyped(json, false);
}

export function PlantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'location': json['location'] == null ? undefined : json['location'],
        'capacityKw': json['capacityKw'] == null ? undefined : json['capacityKw'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PlantToJSON(json: any): Plant {
    return PlantToJSONTyped(json, false);
}

export function PlantToJSONTyped(value?: Plant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'location': value['location'],
        'capacityKw': value['capacityKw'],
        'status': value['status'],
    };
}

