/**
 * Solar Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Alert { 
    id?: string;
    plantId?: string;
    type?: string;
    message?: string;
    timestamp?: string;
}

