/**
 * Solar Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Plant { 
    id?: string;
    name?: string;
    location?: string;
    capacityKw?: number;
    status?: string;
}

